/**
 * Ipfy TLD Validator
 *
 * Checks a form field's domain against IANA's real TLD list, so
 * ".studio", ".domains", or an internationalized TLD doesn't get
 * silently rejected by a form that only ever expected ".com".
 *
 * Usage — one line per field:
 *   <input type="email" name="email" onblur="TLD.check(this)">
 *   <input type="url"   name="website" onblur="TLD.check(this)">
 *
 * That's it. It auto-detects email vs. URL from the field's type
 * attribute, extracts the domain, checks the TLD, and calls the
 * browser's native setCustomValidity() — which every standard HTML
 * form (Contact Form 7, Fluent Forms, Gravity Forms, or anything else
 * using a normal <form>) already respects for blocking submission and
 * showing an error, with zero plugin-specific integration code.
 *
 * Data (tld.json) is fetched once, automatically, from wherever this
 * script itself was loaded from — no separate include needed. If that
 * fetch hasn't finished yet (or fails) when check() is called, it fails
 * open: nothing gets blocked. A missing/slow data file should never be
 * the reason a real submission gets rejected.
 *
 * GENERATED FILE — do not edit directly. Source of truth is
 * src/core.js (shared with the @ipfy/tld-validator npm package) and
 * the loader logic in scripts/build-browser.js. Regenerate with:
 *   node scripts/build-browser.js
 */
(function (global) {
  'use strict';

/**
 * Ipfy TLD Validator — core logic
 *
 * Environment-agnostic. No window, no document, no fetch — the only
 * global this relies on is URL, which exists in both browsers and
 * Node 18+. Data loading (how tldSet gets populated) and DOM
 * interaction (what "input" actually is) are both the caller's
 * responsibility — this file only knows how to check a hostname/TLD
 * against whatever Set it's given.
 *
 * This file is the single source of truth. Both tld.js (the browser
 * build, generated by scripts/build-browser.js) and index.js (the npm
 * package entry point) build on top of it — neither reimplements this
 * logic separately.
 */

function extractHostname(rawValue, mode) {
  var value = (rawValue || '').trim();
  if (!value) return null;

  if (mode === 'email') {
    var at = value.lastIndexOf('@');
    if (at === -1) return null;
    value = value.slice(at + 1);
  }

  try {
    // Punycode-encodes any Unicode/IDN domain the same way a real DNS
    // lookup would need it — so ಐಪಿಫೈ.ಭಾರತ and münchen.de both work.
    var url = new URL('http://' + value.replace(/^[a-z]+:\/\//i, ''));
    return url.hostname;
  } catch (e) {
    return null;
  }
}

function tldOf(hostname) {
  var parts = String(hostname || '').split('.');
  return parts.length > 1 ? parts[parts.length - 1].toLowerCase() : null;
}

/**
 * Wraps a TLD-set getter into an isKnownTld(tld) function. Takes a
 * getter (not the Set directly) so the underlying data can be swapped
 * out later — e.g. after a live refresh completes — without callers
 * having to re-bind to a new function.
 */
function makeIsKnownTld(getTldSet) {
  return function isKnownTld(tld) {
    var tldSet = getTldSet();
    return !!tldSet && tldSet.has(String(tld || '').toLowerCase());
  };
}

function isValidDomain(isKnownTldFn, rawInput) {
  var hostname = extractHostname(rawInput, 'url');
  if (!hostname) return false;
  var tld = tldOf(hostname);
  return !!tld && isKnownTldFn(tld);
}

/**
 * Factory for the field-checking function behind TLD.check(input, opts).
 * isReadyFn() should report whether TLD data is currently available —
 * callers fail open (never block) before it is. The returned function
 * only ever reads/writes properties on whatever "input" object it's
 * given; it has no reference to any global DOM object itself.
 */
function makeFieldChecker(isKnownTldFn, isReadyFn) {
  return function check(input, opts) {
    opts = opts || {};

    if (!isReadyFn()) {
      input.setCustomValidity('');
      return true; // data not loaded yet — never block on that
    }

    if (!input.value) {
      input.setCustomValidity('');
      return true; // let required/type validation handle empty fields
    }

    var mode = opts.mode || (input.type === 'email' ? 'email' : 'url');
    var hostname = extractHostname(input.value, mode);
    var tld = hostname ? tldOf(hostname) : null;

    if (tld && isKnownTldFn(tld)) {
      input.setCustomValidity('');
      return true;
    }

    if (!hostname) {
      // Value doesn't even parse as a domain — defer to the field's own
      // type="email"/type="url" validation message rather than ours.
      input.setCustomValidity('');
      return false;
    }

    input.setCustomValidity(opts.message || "That domain's ending doesn't look like a real one — please check it.");
    return false;
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { extractHostname, tldOf, makeIsKnownTld, isValidDomain, makeFieldChecker };
}

  var scriptEl = document.currentScript;
  var baseUrl = scriptEl ? scriptEl.src.replace(/tld\.js(\?.*)?$/, '') : '';

  var tldSet = null;
  var ready = fetch(baseUrl + 'tld.json')
    .then(function (res) {
      if (!res.ok) throw new Error('tld.json fetch failed: ' + res.status);
      return res.json();
    })
    .then(function (data) {
      tldSet = new Set(data.tlds || []);
    })
    .catch(function (err) {
      console.warn('[TLD] Could not load tld.json — validation is disabled until it loads. Fields pass through unchecked.', err);
    });

  var isKnownTld = makeIsKnownTld(function () { return tldSet; });
  var check = makeFieldChecker(isKnownTld, function () { return tldSet !== null; });

  global.TLD = {
    check: check,
    isKnownTld: isKnownTld,
    ready: ready,
  };
})(window);
